# nixpacks.toml

# Setup Phase: কোন কোন প্যাকেজ সিস্টেম লেভেলে লাগবে তা বলা হচ্ছে।
# আমরা সরাসরি Python 3.11 এবং Poetry (প্যাকেজ ম্যানেজার) ব্যবহার করতে বলছি।
[phases.setup]
nixPkgs = ["...", "python311", "poetry"]

# Install Phase: প্যাকেজ ইন্সটল করার কমান্ড।
[phases.install]
cmds = [
    "poetry init -n",  # ইনিশিয়ালাইজ করে pyproject.toml তৈরি করবে
    "poetry add $(cat requirements.txt | tr '\n' ' ')", # requirements.txt থেকে প্যাকেজ যোগ করবে
]

# Start Phase: অ্যাপটি কীভাবে চালু করতে হবে।
[start]
cmd = "poetry run gunicorn main:app"
