# nixpacks.toml

# Setup Phase: Python 3.11 এবং Poetry ইন্সটল করা হচ্ছে।
[phases.setup]
nixPkgs = ["...", "python311", "poetry"]

# Install Phase: প্যাকেজ ইন্সটল করার কমান্ড।
[phases.install]
cmds = [
    "poetry init -n",
    # requirements.txt ফাইলের প্রতিটি লাইন লুপ করে poetry দিয়ে প্যাকেজ যোগ করা হচ্ছে।
    # এটি tr কমান্ডের চেয়ে অনেক বেশি নির্ভরযোগ্য।
    "cat requirements.txt | while read -r package; do poetry add \"$package\"; done"
]

# Start Phase: অ্যাপটি কীভাবে চালু করতে হবে।
[start]
cmd = "poetry run gunicorn main:app"
