# nixpacks.toml

# Setup Phase: আমরা ডিফল্ট প্যাকেজ (`...`) বাদ দিয়ে শুধুমাত্র Python 3.11 এবং Poetry নির্দিষ্ট করছি।
# এটি Python ভার্সন কনফ্লিক্ট সমাধান করবে।
[phases.setup]
nixPkgs = ["python311", "poetry", "gcc"] # gcc যোগ করা হয়েছে কারণ কিছু পাইথন প্যাকেজের এটি প্রয়োজন হতে পারে।

# Install Phase: প্যাকেজ ইন্সটল করার কমান্ড।
[phases.install]
cmds = [
    "poetry init -n",
    "cat requirements.txt | while read -r package; do poetry add \"$package\"; done"
]

# Start Phase: অ্যাপটি কীভাবে চালু করতে হবে।
[start]
cmd = "poetry run gunicorn main:app"
